modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="modemachine"
version="1.0.0"
displayName="ModeMachine"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="User, MCreator"

[[dependencies.modemachine]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




